source 'http://rubygems.org'

gem 'rails', '3.2.9'
gem 'haml', '3.1.4'
gem 'sass', '3.2.9'
gem 'pg', '0.11.0'
gem 'json', '1.8.0'
gem 'jquery-rails', '2.0.1'
gem "bcrypt-ruby", '3.0.1', :require => "bcrypt"
gem 'bootstrap-will_paginate', '0.0.9'
gem 'acts-as-taggable-on', '2.2.2'
gem 'paper_trail', '2.7.1'
gem "paperclip", '3.4.1'
gem 'aws-sdk', '1.3.9'
gem 'airbrake', '3.1.5'
gem 'acts_as_list', '0.9.7'
gem 'prawn', '1.3.0'
gem 'prawn-table', '0.2.1'
gem 'prawn-qrcode', '0.2.2.1'
gem 'savon', '2.11.1'
gem 'delayed_job_active_record', '4.1.1'
gem 'daemons', '1.1.9'
gem 'similar_strings', '0.0.1'
gem 'tinymce-rails', '4.5.2'
gem 'nokogiri', '1.5.5'
gem 'httparty', '0.10.2'
gem 'pdf-reader', '2.2.0'
gem 'combine_pdf', '1.0.16'
gem 'simple_captcha', :git => 'git://github.com/galetahub/simple-captcha.git'
gem 'rmagick', '2.16'
gem 'magnific-popup-rails', '1.1.0'
gem 'excon', '0.80.1'
gem 'svg-graph', '2.1.3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'hirb'
  gem 'nifty-generators', '0.4.6'
  gem 'thin'
  gem 'populator'
  gem 'faker', '1.5.0'
# gem 'rack-mini-profiler', '0.9.8'
# gem 'flamegraph'
end
